# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page, on
# https://search.nixos.org/options and in the NixOS manual (`nixos-help`).
# See: https://nixos.org/manual/nixos/stable/
# man configuration.nix

{ config, lib, pkgs, ... }:

let
  # Following variables will be updated by ./install-system.sh - no need to change it
  timeZone = "Europe/Paris";
  defaultLocale = "en_US.UTF-8";
  defaultConsoleKeymap = "us";
in {
  # Split configurations files, see: https://nixos.wiki/wiki/NixOS_modules
  imports =
    [
      ##################### Step 1: Hardware #####################
      # Include the results of the hardware scan.
      # You could re-generated one with 'sudo nixos-generate-config --no-filesystems'.
      # For hardware related configurations, see: https://github.com/NixOS/nixos-hardware
      ./hardware-configuration.nix # Do NOT edit this file !
      ##################### Step 2: Modules #####################
      # Import all modules, activate or deactivate them below
      ./modules/default.nix
      ##################### Step 3: User #####################
      # Me
      ./user-me.nix # edit / change me !
    ];

  # updated by ./install-system.sh - no need to change it
  networking.hostName = "NixCOSMIC";

  # platform updated by ./install-system.sh - do NOT edit.
  nixcosmic.platform.amd64.enable = lib.mkDefault true;
  nixcosmic.platform.rpi4.enable = lib.mkDefault false;

  ######## Enabling or disabling ./modules here:
  # Modern AMD GPU
  nixcosmic.hardware.amdGpu.enable = lib.mkDefault false;
  # Modern Nvidia GPU
  nixcosmic.hardware.nvidiaGpu.enable = lib.mkDefault false;
  # EXPERIMENTAL - laptop battery saver
  nixcosmic.hardware.laptop.enable = lib.mkDefault false;

  # updated by ./install-system.sh - do NOT edit.
  nixcosmic.filesystems.luks.enable = lib.mkDefault true;
  nixcosmic.filesystems.minimal.enable = lib.mkDefault false;

  nixcosmic.bootefi.enable = lib.mkDefault true;
  nixcosmic.desktop.cosmic.enable = lib.mkDefault true; # COSMIC desktop environment
  nixcosmic.desktop.dotfiles.enable = lib.mkDefault true; # Custom Nixos+COSMIC dotfiles by VideoCurio

  nixcosmic.desktop.apps.basics.enable = lib.mkDefault true; # Brave browser, Alacritty, Bitwarden, Signal, Yubico auth, Gimp3, EasyEffects, ProtonVPN gui.
  nixcosmic.desktop.apps.devops.enable = lib.mkDefault false; # Required for apps.devops options below. + Cloudlfared
  nixcosmic.desktop.apps.devops.networks.enable = lib.mkDefault false; # Nmap, Zenmap, Wireshark
  nixcosmic.desktop.apps.devops.python312.enable = lib.mkDefault false; # Python3.12, pip, setuptools, JetBrains PyCharm-Community
  nixcosmic.desktop.apps.devops.rust.enable = lib.mkDefault false; # Rustc, cargo, rust-analyzer, clippy + more, JetBrains RustRover
  nixcosmic.desktop.apps.gaming.enable = lib.mkDefault false; # Steam, Heroic Launcher, gamemoderun, Input-Remapper, TeamSpeak6 client
  nixcosmic.desktop.apps.studio.enable = lib.mkDefault false; # OBS, Audacity, DaVinci Resolve

  nixcosmic.fonts.enable = lib.mkDefault true; # Fira, Noto, some Nerds fonts, JetBrains Mono
  nixcosmic.networking.enable = lib.mkDefault true; # NetworkManager, DNS set to Quad9 and cloudflare.
  nixcosmic.services.enable = lib.mkDefault true; # Flatpak + flathub/cosmic repos, pipewire
  nixcosmic.services.printing.enable = lib.mkDefault false; # CUPS
  nixcosmic.services.sshd.enable = lib.mkDefault false; # SSH daemon
  nixcosmic.services.ai.enable = lib.mkDefault false; # Ollama with mistral-nemo, open-webui
  nixcosmic.shell.zsh.enable = lib.mkDefault true; # ZSH shell, REQUIRED for nixcosmic.desktop.dotfiles.enable
  nixcosmic.virtualisation.enable = lib.mkDefault false; # docker, docker buildx, docker-compose, QEMU/KVM, libvirt, virt-manager

  # Test hardened configurations one by one
  # Check results with: `systemd-analyze security`
  nixcosmic.hardened.accountsDaemon.enable = lib.mkDefault true;
  nixcosmic.hardened.acpid.enable = lib.mkDefault true;
  nixcosmic.hardened.cups.enable = lib.mkDefault (
    config.nixcosmic.services.printing.enable
  );
  nixcosmic.hardened.dbus.enable = lib.mkDefault true;
  nixcosmic.hardened.display-manager.enable = lib.mkDefault false;
  nixcosmic.hardened.docker.enable = lib.mkDefault false;
  nixcosmic.hardened.getty.enable = lib.mkDefault false; # WARNING: will prevent TTY console login
  nixcosmic.hardened.networkManager.enable = lib.mkDefault false; # TODO: proton-vpn bug if set to true
  nixcosmic.hardened.networkManager-dispatcher.enable = lib.mkDefault false; # TODO: proton-vpn bug if set to true
  nixcosmic.hardened.nix-daemon.enable = lib.mkDefault true;
  nixcosmic.hardened.nscd.enable = lib.mkDefault true;
  nixcosmic.hardened.rescue.enable = lib.mkDefault true;
  nixcosmic.hardened.rtkit-daemon.enable = lib.mkDefault true;
  nixcosmic.hardened.sshd.enable = lib.mkDefault (
    config.nixcosmic.services.sshd.enable
  );
  nixcosmic.hardened.user.enable = lib.mkDefault false; # TODO: 'Flatpak run' bug if set to true
  nixcosmic.hardened.wpa_supplicant.enable = lib.mkDefault true;

  # TODO: Prevent some conflicts between modules:

  ############# Settings belows this line should not be changed! #############

  # Set your time zone.
  time.timeZone = timeZone;

  # Select internationalisation properties. See 'locale' and 'locale -a'
  i18n = {
    defaultLocale = defaultLocale;
    extraLocales = "all"; # Support all glibc locales
    extraLocaleSettings = {
      LC_ADDRESS = defaultLocale;
      LC_IDENTIFICATION = defaultLocale;
      LC_MEASUREMENT = defaultLocale;
      LC_MONETARY = defaultLocale;
      LC_NAME = defaultLocale;
      LC_NUMERIC = defaultLocale;
      LC_PAPER = defaultLocale;
      LC_TELEPHONE = defaultLocale;
      LC_TIME = defaultLocale;
    };
    #inputMethod = {
    #  type = "fcitx5";
    #  enable = true;
    #  fcitx5.waylandFrontend = true;
    #  fcitx5.addons = with pkgs; [
    #    fcitx5-gtk
    #    fcitx5-chinese-addons  # table input method support
    #    fcitx5-nord            # a color theme
    #  ];
    #};
  };

  console = {
    #font = "Lat2-Terminus16";
    keyMap = defaultConsoleKeymap;
    earlySetup = true; # initrd setup
    useXkbConfig = false; # use xkb.options in tty.
  };

  # List packages installed in system profile.
  # You can use https://search.nixos.org/ to find more packages (and options).
  environment.systemPackages = with pkgs; [
    # Basics
    wget
    curl
    fastfetch
    killall
    git
    gnupg
    pinentry-curses
    gnused
    pciutils
  ]
  ++ (
    if config.nixcosmic.hardware.amdGpu.enable then
      [ btop-rocm ]
    else
      if config.nixcosmic.hardware.nvidiaGpu.enable then
        [ btop-cuda ]
      else
        [ btop ]
  );

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  #programs.mtr.enable = true;
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = false; # Let's programs.ssh.startAgent do this job
    pinentryPackage = pkgs.pinentry-curses;
  };

  # Enabling Linux AppImage
  #programs.appimage.enable = true;
  #programs.appimage.binfmt = true;

  # Allow unfree packages, could be overridden by some modules.
  nixpkgs.config.allowUnfree =
    if config.nixcosmic.hardware.nvidiaGpu.enable then
      true
    else
      if config.nixcosmic.desktop.apps.gaming.enable then
        true
      else
        false
  ;

  # Automatic OS updates and cleanup
  system.autoUpgrade.enable = true;
  system.autoUpgrade.dates = "03:40";
  # Reboot on new kernel, initrd or kernel module.
  #system.autoUpgrade.allowReboot = true;
  # Collect garbage
  nix.gc.automatic = true;
  nix.gc.dates = "daily";
  nix.gc.options = "--delete-older-than 7d";
  nix.settings.auto-optimise-store = true;

  # Copy the NixOS configuration file and link it from the resulting system
  # (/run/current-system/configuration.nix). This is useful in case you
  # accidentally delete configuration.nix.
  # system.copySystemConfiguration = true;

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "25.05"; # Did you read the comment?
}
