# Do NOT Edit this file - it was generated by 'curios-install'
# and may be overwritten by future updates. Users can edit /etc/nixos/settings.nix instead.

{ config, lib, pkgs, ... }:

let
  curiosModules = if builtins.pathExists ./modules.json then
    builtins.fromJSON (builtins.readFile ./modules.json)
  else
    { };
in {
  # Split configurations files, see: https://nixos.wiki/wiki/NixOS_modules
  imports = [
    ##################### Step 1: Hardware #####################
    # Include the results of the hardware scan.
    # You could re-generated one with 'sudo nixos-generate-config --no-filesystems'.
    # For hardware related configurations, see: https://github.com/NixOS/nixos-hardware
    # Do NOT edit on an installed system. The stub is used only when building the ISO seed.
    (if builtins.pathExists ./hardware-configuration.nix then
      ./hardware-configuration.nix
    else
      ./iso/hardware-stub.nix)
    ##################### Step 2: Modules #####################
    # Import all modules, activate or deactivate them in settings.nix
    ./modules/default.nix
    ##################### Step 3: User Settings #####################
    # User custom settings
    ./settings.nix
  ];

  # Importing curios modules settings from JSON files
  curios = curiosModules.curios or { };

  ############# Settings belows this line should not be changed! #############

  # Select internationalisation properties. See 'locale' and 'locale -a'
  i18n = {
    defaultCharset = "UTF-8";
    extraLocales = "all"; # Support all glibc locales
    extraLocaleSettings = {
      LC_ADDRESS = config.curios.system.i18n.locale;
      LC_IDENTIFICATION = config.curios.system.i18n.locale;
      LC_MEASUREMENT = config.curios.system.i18n.locale;
      LC_MONETARY = config.curios.system.i18n.locale;
      LC_NAME = config.curios.system.i18n.locale;
      LC_NUMERIC = config.curios.system.i18n.locale;
      LC_PAPER = config.curios.system.i18n.locale;
      LC_TELEPHONE = config.curios.system.i18n.locale;
      LC_TIME = config.curios.system.i18n.locale;
    };
    #inputMethod = {
    #  type = "fcitx5";
    #  enable = true;
    #  fcitx5.waylandFrontend = true;
    #  fcitx5.addons = with pkgs; [
    #    fcitx5-gtk
    #    fcitx5-chinese-addons  # table input method support
    #    fcitx5-nord            # a color theme
    #  ];
    #};
  };

  # List packages installed in system profile.
  # You can use https://search.nixos.org/ to find more packages (and options).
  environment.systemPackages = with pkgs;
    [
      # Basics
      wget
      curl
      fastfetch
      busybox
      git
      gnupg
      pinentry-curses
      gnused
      pciutils
      smartmontools
    ] ++ lib.optionals config.services.desktopManager.cosmic.xwayland.enable
    [ wl-clipboard ] ++ lib.optionals config.curios.hardware.amdGpu.enable [
      btop-rocm
      nvtopPackages.amd
    ] ++ lib.optionals config.curios.hardware.nvidiaGpu.enable [
      btop-cuda
      nvtopPackages.nvidia
    ] ++ lib.optionals (!config.curios.hardware.nvidiaGpu.enable
      && !config.curios.hardware.amdGpu.enable) [ btop ];

  # Set environment variables here:
  environment.sessionVariables = {
    # For rust cargo
    PKG_CONFIG_PATH =
      "/run/current-system/sw/lib/pkgconfig:${pkgs.openssl.dev}/lib/pkgconfig:${pkgs.libxkbcommon.dev}/lib/pkgconfig";
  };

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  #programs.mtr.enable = true;
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = false; # Let's programs.ssh.startAgent do this job
    pinentryPackage = pkgs.pinentry-curses;
  };

  # Allow unfree packages, could be overridden by some modules.
  nixpkgs.config.allowUnfree = if config.curios.hardware.nvidiaGpu.enable then
    true
  else if config.curios.desktop.ai.cursor.enable then
    true
  else if config.curios.desktop.office.enable then
    true
  else if config.curios.desktop.chat.teamspeak.enable then
    true
  else if config.curios.desktop.gaming.enable then
    true
  else if config.curios.desktop.studio.enable then
    true
  else if config.curios.desktop.devops.editor.go.enable then
    true
  else if config.curios.desktop.devops.editor.rust.enable then
    true
  else if config.curios.others.p7zip.enable then
    true
  else
    false;

  system = {
    # Automatic OS updates and cleanup
    autoUpgrade = {
      # The URI of the NixOS channel to use for automatic upgrades.
      channel = "https://channels.nixos.org/nixos-26.05";
    };
    # Copy the NixOS configuration file and link it from the resulting system
    # (/run/current-system/configuration.nix). This is useful in case you
    # accidentally delete configuration.nix.
    copySystemConfiguration = true;
    # CuriOS variant version
    nixos.variantName = "CuriOS";
    nixos.variant_id = "unstable-20260909.1242";
  };

  nix = {
    settings = {
      auto-optimise-store = true;
      # Allowing Flakes
      experimental-features = [ "nix-command" "flakes" ];
      # A list of names of users that are allowed to connect to the Nix daemon
      allowed-users = [ "root" "@wheel" ];
      # List of users that have additional rights when connecting to the Nix daemon.
      trusted-users = [ "@wheel" ];
    };
  };
}
