# System users should be defined here - it was generated by 'nixcosmic-install'
# and may be overwritten by future updates.
# Must be imported by configuration.nix

{ config, lib, pkgs, ... }:

let
  # Following variables can be edited.
  # Default user password. Change it later, after your first boot with COSMIC Parameters > System & Accounts
  # OR with the 'passwd' command line.
  # Do **NOT** set your real password HERE !
  password = "changeme";
in {
  users.mutableUsers = true;
  # Define a user account
  # <user> name will be updated by nixcosmic-install during ISO install
  users.users.nixos = {
    isNormalUser = true;
    initialPassword = password;
    extraGroups =  [
      "wheel"
      "audio"
      "sound"
      "video"
    ]
    ++ lib.optionals config.nixcosmic.networking.enable [
      "networkmanager"
    ]
    ++ lib.optionals config.nixcosmic.virtualisation.enable [
      "docker"
      "libvirtd"
      "qemu-libvirtd"
      "kvm"
      "input"
      "disk"
    ];
    useDefaultShell = true;
  };

}
